#This form is for Schedule B - Interest and ordinary Dividends

[Part1_Interest]
    i1 = ["Payer1 = 120", "Payer2 = 300", "Payer3 = 260"]
    i2 = 0 # prog.
    i3 = 0 #excludable interest - form 8815
    i4 = 0 #prog.

[Part2_Ordinary_Dividends]
    i5 = ["Payer1 = 430", "Payer2 = 200", "Payer3 = 780"]
    i6 = 0 #prog.

[Part3_Foreign_Accounts_Trusts]
    i7a = "No" #foreign bank and financial account
    i7b = "" #foreign country name
    i8 = "No" #money from foreign trust - form 3520
    
